### ISSUE TITLE
CMAKE package dependencies

### ISSUE THREAD

**Issue by ElectricSolstice** [dradtke/allegro_tiled#8]
The cmake file could probably use some changes for alternative names for allegro-5.0.pc and allegro_image-5.0.pc. I have these files in a custom location where pkg-config knows where they are. However, they were installed as allegro-5.pc and allegro_image-5.pc, so I got an error at first when using cmake. Was easy enough for me to create symlinks to them, but would be nice if this package detected these names on its own. If it's of any importance, I am using the latest allegro (5.1) available at the time of this writing.

![allegro_package_naming1](https://cloud.githubusercontent.com/assets/5295371/6681169/3a8e515a-cc1f-11e4-9eb4-1e80ea65df0d.png)

**Comment by dradtke** [comment]
Is there any official Allegro documentation for how package config files are supposed to be named? I'm curious if these will change with each point release, or if `allegro-5.pc` is a safe assumption until the release of Allegro 6.

**Comment by ElectricSolstice** [comment]
I haven't been able to find any documentation about this.

**Comment by dradtke** [comment]
@ElectricSolstice , can you try checking out the `cmake_pkg_deps` branch and see if that works for you? I changed CMakeLists to check for `allegro-5.pc` and fall back to `allegro-5.0.pc` if it's not found.

**Comment by ElectricSolstice** [comment]
When I try that branch, I get this error.

```
cmake .
CMake Error at CMakeLists.txt:27 (pkg_search_modules):
  Unknown CMake command "pkg_search_modules".


-- Configuring incomplete, errors occurred!

```

**Comment by dradtke** [comment]
Alright, I think I finally got it working. Can you give the `cmake_pkg_deps` branch another shot?

**Comment by ElectricSolstice** [comment]
It's working now on my computer.

**Comment by dradtke** [comment]
Cool, feel free to open comment here if this becomes an issue again.
